set -g mouse on
set -g default-terminal "tmux-256color"
set -g display-time 4000
set -g status-position bottom
set -g lock-command vlock
set -g lock-after-time 0

set -g history-limit 20000
set -g base-index 1


set -g status-right "%H:%M"
set -g window-status-current-style "underscore"

set-option -g repeat-time 0

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set-window-option -g mode-keys vi
setw -g mode-keys vi

bind-key -n M-Enter copy-mode

bind P paste-buffer
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi r send-keys -X rectangle-toggle
bind-key -T copy-mode-vi  Up     send-keys  -X  cursor-up
bind-key -T copy-mode-vi  Down   send-keys  -X  cursor-down

bind-key -T copy-mode-vi  Home  send-keys  -X  back-to-indentation      
bind-key -T copy-mode-vi  End   send-keys  -X  end-of-line

bind-key -T copy-mode-vi y send-keys -X copy-pipe 'xsel -ib'
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'xsel -ib'

# style
set -g status-bg "#000000"
set -g status-fg "#c0c0c0"

set -g status-right "#H %H:%M %d-%b-%y"

set -g pane-active-border-style fg=blue

# open new panes with the same working directory
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind J split-window -c "#{pane_current_path}" -l 16
bind L split-window -h -c "#{pane_current_path}"
bind X lock-session

# -----------------------------------------------------------------------------------

#
# set -g mouse on
# set -g default-terminal "tmux-256color"
# set -g display-time 4000
# set -g status-position bottom
# set -g lock-command vlock
# set -g lock-after-time 0
#
# # enable vi mode
# set-window-option -g mode-keys vi
#
# # keep default prefix for others convenience
# unbind C-b
# set -g prefix C-Space
# bind C-Space send-prefix
# set -g prefix2 C-b
#
# # style
# set -g status-bg "#000000"
# set -g status-fg "#c0c0c0"
#
# set -g status-right "#H %H:%M %d-%b-%y"
# # set -g status-style fg=black,bg=default
# # set-option -g status-style bg=default
#
# set -g pane-active-border-style fg=blue
#
# # open new panes with the same working directory
# bind '"' split-window -c "#{pane_current_path}"
# bind % split-window -h -c "#{pane_current_path}"
#
# bind J split-window -c "#{pane_current_path}" -l 16
# bind L split-window -h -c "#{pane_current_path}"
#
# # -T mode_specific_to
# bind	-T prefix		r source-file "~/.tmux.conf"
# bind	-T prefix		i copy-mode
# bind	-T prefix		H copy-mode \; send -X search-backward "^\\\$ "
# bind	-T copy-mode-vi	H send -X search-again \; send -X scroll-top
# bind	-T prefix		R command-prompt -I "resize-pane -y "
#
# bind    -T copy-mode-vi y send -X select-word
# bind -n -T copy-mode-vi Y send-keys B \; send -X begin-selection \; send-keys E
#
# bind X lock-session
